"""password hashing 128 made

Revision ID: 79290f3f6528
Revises: a208bdca27e3
Create Date: 2024-11-07 19:58:39.788083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79290f3f6528'
down_revision = 'a208bdca27e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
